mod agent_session;
mod attachment;
mod conversation;
mod course;
mod domain;
mod event;
mod extension;
mod id;
mod import;
mod model;
mod orchestration;
mod policy;
mod project;
mod state;

pub use agent_session::*;
pub use attachment::*;
pub use conversation::*;
pub use course::*;
pub use domain::*;
pub use event::*;
pub use extension::*;
pub use id::*;
pub use import::*;
pub use model::*;
pub use orchestration::*;
pub use policy::*;
pub use project::*;
pub use state::*;

use schemars::schema_for;
use ts_rs::{Config, TS};

const GENERATED_HEADER: &str = "// Generated by lunascope-core. Do not edit by hand.\n\n\
export type JsonPrimitive = string | number | boolean | null;\n\
export type JsonValue = JsonPrimitive | { [key: string]: JsonValue } | JsonValue[];\n\n";

/// Returns the deterministic TypeScript contract generated from the canonical
/// Rust types. The checked-in copy is verified by tests.
pub fn typescript_contract() -> String {
    let config = Config::default();
    let declarations = [
        EventId::decl(&config),
        ProjectId::decl(&config),
        ThreadId::decl(&config),
        RunId::decl(&config),
        OrchestrationId::decl(&config),
        WorkerId::decl(&config),
        CorrelationId::decl(&config),
        ArtifactId::decl(&config),
        CheckpointId::decl(&config),
        AgentSessionId::decl(&config),
        AgentSessionKind::decl(&config),
        AgentSessionState::decl(&config),
        AgentSessionRecord::decl(&config),
        RunLeaseRecord::decl(&config),
        RunState::decl(&config),
        WorkerState::decl(&config),
        RiskLevel::decl(&config),
        RedactionState::decl(&config),
        EventSource::decl(&config),
        VerificationStatus::decl(&config),
        CompletionKind::decl(&config),
        AgentPlanStepStatus::decl(&config),
        AgentPlanStep::decl(&config),
        AgentPlan::decl(&config),
        ReasoningSummarySource::decl(&config),
        ReasoningSummaryRecord::decl(&config),
        TransportRetryRecord::decl(&config),
        ConversationRole::decl(&config),
        ConversationThread::decl(&config),
        ConversationMessage::decl(&config),
        RunContinuationSummary::decl(&config),
        ThreadContextSummary::decl(&config),
        ThreadContextWindow::decl(&config),
        AttachmentKind::decl(&config),
        ImportedAttachment::decl(&config),
        UltraNoteMode::decl(&config),
        CourseSourceKind::decl(&config),
        NoteProvenance::decl(&config),
        HomeworkKind::decl(&config),
        HomeworkAssistanceMode::decl(&config),
        Course::decl(&config),
        CourseThreadBinding::decl(&config),
        CourseSource::decl(&config),
        CourseSearchHit::decl(&config),
        CitationAnchor::decl(&config),
        SyllabusStructure::decl(&config),
        SyllabusRevision::decl(&config),
        NoteSection::decl(&config),
        NoteRevision::decl(&config),
        CourseConcept::decl(&config),
        CourseAssignment::decl(&config),
        ReviewItem::decl(&config),
        CourseMemory::decl(&config),
        HomeworkPolicyDecision::decl(&config),
        UltraNoteWorkspace::decl(&config),
        DomainPackId::decl(&config),
        GameEngine::decl(&config),
        DomainPackDescriptor::decl(&config),
        DomainDetection::decl(&config),
        ProgrammingFlowEvidence::decl(&config),
        GameDevelopmentFlowEvidence::decl(&config),
        ResearchSourceEvidence::decl(&config),
        ResearchFlowEvidence::decl(&config),
        AcademicWritingFlowEvidence::decl(&config),
        FrontendFlowEvidence::decl(&config),
        DomainFlowEvidence::decl(&config),
        PermissionDecision::decl(&config),
        ModelSelection::decl(&config),
        DelegationKind::decl(&config),
        DelegationDecision::decl(&config),
        WorkerInputContext::decl(&config),
        WorkerOutputSchema::decl(&config),
        WorkerBudget::decl(&config),
        AllowedWorkerModel::decl(&config),
        RetryPolicy::decl(&config),
        WorkerCheckpointPolicy::decl(&config),
        WorkerField::decl(&config),
        WorkerSpec::decl(&config),
        OrchestrationPatchApplyMode::decl(&config),
        WorkerPatch::decl(&config),
        OrchestrationPatchOperation::decl(&config),
        OrchestrationPatch::decl(&config),
        UserOverrideRecord::decl(&config),
        OrchestrationPlan::decl(&config),
        OrchestrationSession::decl(&config),
        OrchestrationValidation::decl(&config),
        HandoffRecord::decl(&config),
        WorkerExecutionRecord::decl(&config),
        WorkerStateChange::decl(&config),
        OrchestrationRunResult::decl(&config),
        ToolCall::decl(&config),
        ToolResult::decl(&config),
        ApprovalRequest::decl(&config),
        ApprovalResolution::decl(&config),
        ArtifactRecord::decl(&config),
        CheckpointRecord::decl(&config),
        VerificationSeverity::decl(&config),
        CriterionVerificationStatus::decl(&config),
        CriterionVerification::decl(&config),
        VerificationFinding::decl(&config),
        VerificationRecord::decl(&config),
        FileChangeKind::decl(&config),
        DiffLineKind::decl(&config),
        DiffLine::decl(&config),
        DiffHunk::decl(&config),
        WorkspaceFileChange::decl(&config),
        OrchestrationChangeSet::decl(&config),
        RunControlKind::decl(&config),
        RunControlStatus::decl(&config),
        RunControlRecord::decl(&config),
        AgentKind::decl(&config),
        AgentActivityItem::decl(&config),
        OrchestrationPlanningStage::decl(&config),
        OrchestrationDraftWorker::decl(&config),
        OrchestrationPlanningActivity::decl(&config),
        SupervisorDecisionKind::decl(&config),
        SupervisorDecisionRecord::decl(&config),
        OrchestrationRevisionRecord::decl(&config),
        EventType::decl(&config),
        EventData::decl(&config),
        EventEnvelope::decl(&config),
        RuntimeSnapshot::decl(&config),
        RuntimeDelta::decl(&config),
        PermissionKind::decl(&config),
        PolicyDecision::decl(&config),
        PolicyScope::decl(&config),
        PolicyRule::decl(&config),
        PermissionContext::decl(&config),
        PermissionRequest::decl(&config),
        PolicyOutcome::decl(&config),
        ToolManifest::decl(&config),
        ProviderType::decl(&config),
        ProviderProtocol::decl(&config),
        CredentialReference::decl(&config),
        ProviderHeaderValue::decl(&config),
        ProviderHeader::decl(&config),
        ProviderConfig::decl(&config),
        ModelCapability::decl(&config),
        ModelRole::decl(&config),
        ReasoningEffort::decl(&config),
        ReasoningEffortProfile::decl(&config),
        ModelAssignment::decl(&config),
        ModelSelectionSettings::decl(&config),
        ModelProfile::decl(&config),
        RoutingPriorities::decl(&config),
        ModelRoutingPolicy::decl(&config),
        ProjectFolder::decl(&config),
        ProjectKind::decl(&config),
        UltraNoteProjectConfig::decl(&config),
        LunaProject::decl(&config),
        UiLanguage::decl(&config),
        ModelReplyLanguage::decl(&config),
        UserPreferences::decl(&config),
        ProjectFileRead::decl(&config),
        ProjectFileMutation::decl(&config),
        RoleProviderPreference::decl(&config),
        NaturalLanguageRoutingDraft::decl(&config),
        ModelRoutingRequest::decl(&config),
        ModelRoutingDecision::decl(&config),
        ModelUsageRecord::decl(&config),
        SkillSourceKind::decl(&config),
        SkillCompatibility::decl(&config),
        SkillSummary::decl(&config),
        LoadedSkill::decl(&config),
        McpConfigValue::decl(&config),
        McpHeader::decl(&config),
        McpTransportConfig::decl(&config),
        McpServerConfig::decl(&config),
        McpToolDescriptor::decl(&config),
        McpServerStatus::decl(&config),
        McpInvocationResult::decl(&config),
        ToolRoutingRequest::decl(&config),
        ToolRouteRejection::decl(&config),
        ToolRoutingDecision::decl(&config),
        ImportComponentKind::decl(&config),
        ImportRiskKind::decl(&config),
        GithubImportSource::decl(&config),
        ImportFileRecord::decl(&config),
        ImportComponent::decl(&config),
        LicenseStatus::decl(&config),
        LicenseFinding::decl(&config),
        GithubImportPreview::decl(&config),
        ImportInstallRequest::decl(&config),
        InstalledImportVersion::decl(&config),
        ImportComparison::decl(&config),
    ];

    let declarations = declarations
        .into_iter()
        .map(|declaration| {
            format!("export {declaration}")
                .lines()
                .map(str::trim_end)
                .collect::<Vec<_>>()
                .join("\n")
        })
        .collect::<Vec<_>>();
    format!("{GENERATED_HEADER}{}\n", declarations.join("\n\n"))
}

/// Returns a pretty, stable JSON Schema for the persisted event envelope.
pub fn event_schema() -> Result<String, serde_json::Error> {
    serde_json::to_string_pretty(&schema_for!(EventEnvelope)).map(|schema| schema + "\n")
}
